// Code generated by Kitex v0.8.0. DO NOT EDIT.
package speedyread

import (
	server "github.com/cloudwego/kitex/server"
	speedy_read "speedy/read/kitex_gen/speedy_read"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler speedy_read.SpeedyRead, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
